var modules =
[
    [ "AtCommand serial", "group__serial.html", null ],
    [ "Command Handler", "group__commandhandler.html", null ],
    [ "Date and time functions", "group__datetime.html", "group__datetime" ],
    [ "Debug functions", "group__debug.html", null ],
    [ "Delegate", "group__delegate.html", null ],
    [ "File system", "group__filesystem.html", null ],
    [ "GPIO functions", "group__gpio.html", null ],
    [ "Hardware PWM functions", "group__hw__pwm.html", null ],
    [ "Hardware timer", "group__hwtimer.html", null ],
    [ "Interrupt functions", "group__interrupts.html", null ],
    [ "Libraries", "group__libraries.html", "group__libraries" ],
    [ "Print stream functions", "group__print.html", null ],
    [ "Pulse width modulation", "group__pwm.html", null ],
    [ "RC Servo functions", "group__Servo.html", null ],
    [ "SPI Hardware support", "group__hw__spi.html", null ],
    [ "SPI support classes", "group__base__spi.html", null ],
    [ "Sming constant values", "group__constants.html", null ],
    [ "Sming event handlers", "group__event__handlers.html", null ],
    [ "Sming structures", "group__structures.html", null ],
    [ "Stream functions", "group__stream.html", null ],
    [ "System", "group__system.html", null ],
    [ "Timer functions", "group__timer.html", null ],
    [ "Watchdog Timer", "group__wdt.html", null ],
    [ "Websocket Client", "group__wsclient.html", null ],
    [ "Websocket Frame", "group__wsframe.html", null ],
    [ "WiFi Access Point", "group__wifi__ap.html", null ],
    [ "WiFi Station Interface", "group__wifi__sta.html", null ]
];